services:
  img2gallery:
    image: ghcr.io/qwisedev/img2gallery:latest
    pull_policy: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      TZ: Asia/Shanghai
      APP_TIMEZONE: Asia/Shanghai
    volumes:
      - img2gallery-data:/data

volumes:
  img2gallery-data:
